### ISSUE TITLE
Trazer uma noção geral da tecnologia para a equipe - Mineração dos dados

### ISSUE THREAD

**Issue by Ninja-Haiyai** [unb-mds/2024-1-Squad12#2]
-Trazer uma breve introdução das tecnologias que poderiam ser usadas com python para o time e a resolução do projeto

**Comment by victorcamaraa** [comment]
usar a api do querido diario
https://queridodiario.ok.org.br/api/docs#
site para codigo dos municipios
https://www.ibge.gov.br/explica/codigos-dos-municipios.php
